version: '3'

services:
  couchserver:
    image: couchdb:3.3.2
    restart: always
    networks:
      - web
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password123
    volumes:
        - ./dbdata:/opt/couchdb/data

  api:
    build: .
    working_dir: /home/appuser/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - ./:/home/appuser
    depends_on:
      - couchserver
    networks:
      - web
networks:
  web:
    driver: bridge
